"""
Bitmaps image assets for Natro Macro
Converted from bitmaps.ahk
"""

bitmaps = {
    "makehoney": "iVBORw0KGgoAAAANSUhEUgAAABkAAAAOAQMAAADg9CUDAAAABlBMVEUAAAD3//lCqWtQAAAAAXRSTlMAQObYZgAAAFFJREFUeAEBRgC5/wDgAAOAAOAAA4AA4AADgADh/4OAAOB/g4AA4H4DgADgPgOAAOAYA4AA4BgDgADgGAOAAOAYA4AA4AgDgADgAAOAAOAAA4BWYxcOMd0SeAAAAABJRU5ErkJggg==",
    "collectpollen": "iVBORw0KGgoAAAANSUhEUgAAACoAAAARAQMAAACRsKx2AAAABlBMVEUAAAD3//lCqWtQAAAAAXRSTlMAQObYZgAAACdJREFUeNpjYGBgkP/BAAICDA7Yqf9/wFRzE5hqZGKQPwCmBBjIpgBvTw8FgJZmfwAAAABJRU5ErkJggg==",
}
